### ISSUE TITLE
Fix the timer calculations

### ISSUE THREAD

**Issue by sbordeyne** [Dogeek/rpg-text#1]
the time/date doesn't quite match, need to rethink the calculations.

**Comment by Rosswell** [comment]
Doesn’t match with what? I can take this on

**Comment by sbordeyne** [comment]
The timer should display the date in the following format :

`[day_of_week_name], the [n_day_in_month][st/nd/rd/th] of [month_name], Year [year_number]`

The only measure of "time" is the number of turns that has elapsed. Each turn is 10 minutes.

The calendar can have as many months as desired, with as many days per month as deesired and so on.
